### ISSUE TITLE
Grouping Layers

### ISSUE THREAD

**Issue by lucsch** [terranum-ch/ToolMap#178]
It would be nice to be able to create layer groups in the table of content. Beside of allowing a better layer classification, groups must support following operations:
 - Hide all layers
 - Show all layers
 - Remove all layers

 _Imported from trac ticket #178,  created by lucsch on 09-08-2011 at 11:42, last modified: 10-11-2013 at 09:45_

**Comment by pascalhorton** [comment]
See #477
