### ISSUE TITLE
Add a link to other open-source GIS software from www.toolmap.ch

### ISSUE THREAD

**Issue by lucsch** [terranum-ch/ToolMap#213]
We should provide a link to other open source GIS software such as QGIS from our website (http://www.toolmap.ch)

 _Imported from trac ticket #213,  created by lucsch on 01-30-2012 at 14:27, last modified: 10-11-2013 at 09:45_

**Comment by pascalhorton** [comment]
See #477

**Comment by pascalhorton** [comment]
Not relevant.
