### ISSUE TITLE
Multiple users working on same project

### ISSUE THREAD

**Issue by lucsch** [terranum-ch/ToolMap#224]
Find a way to split a project and merge it back easily (import external project)

 _Imported from trac ticket #224,  created by lucsch on 01-30-2012 at 15:12, last modified: 10-11-2013 at 09:45_

**Comment by lucsch** [comment]
In [changeset:1338]:
{{{
#!CommitTicketReference repository="" revision="1338"
[see #224] Updating toolmerge build script
}}}

_Trac comment by lucsch on 11-02-2012 at 11:03_

**Comment by lucsch** [comment]
In [changeset:1339]:
{{{
#!CommitTicketReference repository="" revision="1339"
[see #224] Updating toolmerge, comparing project with new database structure is now supported
}}}

_Trac comment by lucsch on 11-02-2012 at 16:48_

**Comment by pascalhorton** [comment]
Implemented in the improved merge tool.
