### ISSUE TITLE
Improve concatenated export (lines)

### ISSUE THREAD

**Issue by lucsch** [terranum-ch/ToolMap#355]
Actually, all line kinds are exported into the same column. It would be better to export kinds belonging to lines constructing polygons into another column.

 _Imported from trac ticket #355,  created by lucsch on 12-09-2013 at 16:53, last modified: 12-09-2013 at 16:53_

**Comment by lucsch** [comment]
Not for the Meyrin milestone, will be in the next milestone

**Comment by pascalhorton** [comment]
See #379

**Comment by pascalhorton** [comment]
See #379
