### ISSUE TITLE
In edition mode, a message saying that ToolMap cannot attribute an object kind appears

### ISSUE THREAD

**Issue by pascalhorton** [terranum-ch/ToolMap#412]
However, it appears when cutting lines (Create intersection or Cut line) and not when adding an attribute.
Message:
![unnamed](https://user-images.githubusercontent.com/5717161/32504207-8cd23fde-c3df-11e7-88b7-222367d905d8.png)

**Comment by lucsch** [comment]
@pascalhorton 

I wasn't able to reproduce this bug on OS X.

I tried:
- Cutting line without attribution
- Cutting line with attribution
- Cutting line with advanced attribution (kind + attributes) 

And nothing issued this message

**Comment by pascalhorton** [comment]
@lucsch : I could reproduce it only by creating a new empty project and adding very minimal object kinds / attributes. The warning arises when cutting a line associated with an object kind with no attribute
