### ISSUE TITLE
Issue with MySQL

### ISSUE THREAD

**Issue by pascalhorton** [terranum-ch/ToolMap#463]
On some computers, the following error message appears when opening a project: 

MySQL Error : Shutting down plugin "binlog"

**Comment by lucsch** [comment]
We may get more information relative to this problem if the end user can use the new #464 feature (see the dialog bellow) and report back the following files :
- toolmap_mysql_log.sql
- toolmap_mysql_err.err

![log_database](https://user-images.githubusercontent.com/25485796/114619460-e0833280-9caa-11eb-8d1c-90265df99ea6.png)

**Comment by lucsch** [comment]
The exact path of the above files is displayed, when opening a project, in the log window (Ctrl+L)

**Comment by lucsch** [comment]
Will be corrected by using MariaDB
