### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by pascalhorton** [terranum-ch/ToolMap#470]
**Objective**: ToolMap's performance is not always optimal and the display can be a bit slow for projects with many elements. The response speed of the software can be improved to make the user experience more pleasant and efficient.
**Technical details**: The identification of elements that slow down the use of the software can be done with profiling tools. These elements can then be improved. The use of multiple threads through the integration of the OpenMP library offers promising prospects.

**Comment by lucsch** [comment]
closed by fe9bc250629171d579392ae846a6c5d62125fc02
